# Generated by Django 5.2.10 on 2026-01-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время начала выполнения привычки",
                        null=True,
                        verbose_name="Время начала",
                    ),
                ),
                ("action", models.CharField(help_text="Укажите действие", max_length=200, verbose_name="Действие")),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1, help_text="Укажите периодичность выполнения привычки", verbose_name="Периодичность"
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_execution",
                    models.IntegerField(
                        blank=True,
                        default=120,
                        help_text="Укажите время выполнения привычки (в секундах)",
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="Признак публичности", verbose_name="Публичность"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
